FROM golang:1.18 AS builder

RUN mkdir /auth-app
ADD . /auth-app
WORKDIR /auth-app

RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -o auth-app cmd/auth_svc/main.go

FROM alpine:latest AS production
COPY --from=builder /auth-app .
CMD ["./auth-app", "server"]